builds:
- main: ./
  flags: -a -tags netgo
  ldflags: |
    -s -w
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
nfpms:
  -
    package_name: prometheus-downsampler
    homepage: https://github.com/mtanda/prometheus-downsampler
    maintainer: Mitsuhiro Tanda
    description: prometheus downsampler
    license: Apache License 2.0
    file_name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    contents:
      - src: "packaging/deb/etc/default/prometheus-downsampler"
        dst: "/etc/default/prometheus-downsampler"
      - src: "packaging/deb/systemd"
        dst: "/usr/lib/systemd/system"
        type: tree
      - dst: /var/tmp/prometheus-downsampler
        type: dir
    scripts:
      postinstall: "packaging/scripts/postinstall.sh"
      postremove: "packaging/scripts/postremove.sh"
      preremove: "packaging/scripts/preremove.sh"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^cut:'
    - '^typo'
