builds:
- main: ./
  flags: -a -tags netgo
  ldflags: |
    -s -w
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
nfpms:
  -
    package_name: prometheus-downsampler
    file_name_template: 'prometheus-downsampler_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    homepage: https://github.com/mtanda/prometheus-downsampler
    maintainer: Mitsuhiro Tanda
    description: prometheus downsampler
    license: Apache License 2.0
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    contents:
      - src: "packaging/deb/etc/default/prometheus-downsampler"
        dst: "/etc/default/prometheus-downsampler"
      - src: "packaging/deb/systemd"
        dst: "/usr/lib/systemd/system"
        type: tree
      - dst: /var/tmp/prometheus-downsampler
        type: dir
    scripts:
      postinstall: "packaging/scripts/postinstall.sh"
      postremove: "packaging/scripts/postremove.sh"
      preremove: "packaging/scripts/preremove.sh"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^cut:'
    - '^typo'
