downsample_config:
  downsample_types:
    - avg
    - max
    - min
  ignore_patterns:
    - foo
relabel_config:
  - source_labels: [__meta_downsampler_downsample_type]
    target_label: downsample_type
    regex: (.*)
    replacement: ${1}