version: "3.8"

volumes:
  prometheus_data: {}
  gohome: {}

networks:
  promapi:


services:
  prometheus:
    image: prom/prometheus:v2.45.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      - promapi
    restart: always

  prometheus-downsampler:
    build:
      context: ./prometheus-downsampler
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
      - gohome:/home/vscode/go:cached
    networks:
      - promapi
    user: vscode
    depends_on:
      - prometheus
